### PR TITLE
Allow feature-redux to accept client-supplied enhancers

### PR DESCRIPTION
**Pull request by sylvainlg**
Implementation for Redux [StoreEnhancer](https://redux.js.org/glossary/#store-enhancer) capability for feature-redux. This change allow every aspect to add a custom enhancer to redux.

__Context__
In order to use Reactotron dev tool, i need to add a custom enhancer to redux.
The aspect i made for this tool :

```js
import Reactotron, { trackGlobalErrors } from 'reactotron-react-native';
import AsyncStorage from '@react-native-community/async-storage';
import { reactotronRedux } from 'reactotron-redux';
import { createAspect } from 'feature-u';

let reactotron = null;

export default createAspect({
  name: 'unusedReactotron',
  genesis: () => {

    if (__DEV__) {
      reactotron = Reactotron.configure({ name: 'my-app' })
        .setAsyncStorageHandler(AsyncStorage) // use react-native-community asyncStorage
        .useReactNative() // add all built-in react native plugins
        .use(trackGlobalErrors()) // add global errors plugin
        .use(reactotronRedux()) // add Redux plugin
        .connect(); // let's connect!
      Reactotron.clear(); // Let's clear Reactotron on every time we load the app
    }
  },
  validateFeatureContent: () => false,
  assembleFeatureContent: () => {},
  getReduxEnhancer: __DEV__
    ? () => reactotron.createEnhancer(true)
    : undefined,
});
```

The current hack is : 

```js
// ...
import { reactotron } from './aspects/reactotron'

// ...

function hackCreateReduxStore(appReducer, middlewareArr) {
  // auto configure Redux DevTools (when detected)
  const { enhancer$, compose$ } = this.reduxDevToolHook$()

  // define our Redux app-wide store WITH optional middleware regsistration
  return middlewareArr.length === 0
    ? createStore(
        rootReducer(appReducer),
        compose$(enhancer$, reactotron.createEnhancer(true))
      ) // NOTE: passing enhancer as last argument requires redux@>=3.1.0
    : createStore(
        rootReducer(appReducer),
        compose$(
          applyMiddleware(...middlewareArr),
          reactotron.createEnhancer(true)
        )
      )
}

// ...

  const reducerAspect = createReducerAspect();
  reducerAspect.config.createReduxStore$ = hackCreateReduxStore.bind(
    reducerAspect.config
  );

```

Note: is reactotron aspect a interesting thing to share ?

### CODE REVIEW

**Comment by KevinAst** [comment]
Hello @sylvainlg,

This looks like a nice enhancement.

While I'm not familiar with redux enhancers, your code looks solid.

I'm running into trouble in my integration testing however.  It's erroring out at the `createStore()` invocation.

- in Chrome browser:

  Error: Expected the reducer to be a function

- in Edge browser:

  Error: The preloadedState argument passed to createStore has unexpected type of "Array". Expected argument to be an object with the following keys: "view", "baseUI", "auth", "location"

The Edge error made me think the 2nd parm (`preloadedState`) to `createStore()` was required, so I supplied an `undefined` in the 2nd position.  This yeilded almost the same result:

- in Chrome browser:

  Error: Expected the reducer to be a function

- in Edge browser:

  Error: Expected the enhancer to be a function

  _This result is very weird ... the same error but with "reducer" in one and "enhancer" in the other ... hmmmm._

I tried removing Redux Dev Tools from the mix, using standard compose ... same ERROR.

Just for fun, I reverted the code back to the original (ignoring enhancers) and it works.

I'm assuming your app is working fine.

I'm wondering if this has something to do with the fact that my app is using `feature-redux-logic` which is introducing middleware through `feature-redux`.

I've checked my code into a "next7" branch.  You can see it [here](https://github.com/KevinAst/feature-redux/blob/next7/src/reducerAspect.js#L246).

Any ideas? ... help help :-)

**Comment by sylvainlg** [comment]
Found it !
I forgot a spread when composing enhancers.

I don't use this code into my application yet (still using the quick and dirty patch), i code that only with unit tests and unit tests don't test the store creation. I fix tests and code.

Can you retry your tests ?

-- 

What about adding an initialState to the config object ?
The feature's reducer must define there own initial state, so maybe this is irrelevant ?
```
initialState$: undefined, // PUBLIC: Initial state => hydrate createStore with those data: Object|undefined
```

**Comment by KevinAst** [comment]
That got me further!

It works, as long as I don't have DevTools enabled in my browser.

With DevTools enabled, it is erroring with:

```
Error: DevTools instrumentation should not be applied more than once.
       Check your store configuration.
```

Need more research on how to configure DevTools when extensions are involved, with the following:

```
window.__REDUX_DEVTOOLS_EXTENSION__
window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__
```

Regarding the `initialState` configuration, I was thinking the same thing.  Not sure it would be a heavily used option, but I suppose it is there for a reason.  I will consider it.

**Comment by KevinAst** [comment]
Hello @sylvainlg,

1. I finally got everything working, including ReduxDevTools integration.

   This type of configuration is always a tedious ... a lot of moving pieces to consider ... and I am always paranoid about breaking someones app.

   I added more comments highlighting exactly what is going on ... both in:
   - `createReduxStore$()`
   - `reduxDevToolHook$()`

   You can see the completed code in my next7 branch: [`reducerAspect.js`](https://github.com/KevinAst/feature-redux/blob/next7/src/reducerAspect.js#L281)

2. I also added the `initialState` config option (which is optional).

   NOTE: Named parameters are used for this. I'm getting away from the "public" promotion of the config object (per our previous discussion).

3. Release Time Frame:

   The release is going to be a bit down the road ... hopefully in the next few days (no promises).

   I am working on a number of enhancements _(both feature-u and some plugins)_, and am wanting to coordinate their release together :-)

4. Speaking of breaking someones app, if you have time and feel like it, you may want to inject my next7 branch reducerAspect.js in your code base to see if it is operable in your environment.

   This is completely up to you ... there may be some problems with this because I added a new dependency (`lodash.isplainobject`).

   You can try it if you like ... not a big deal (I think everything is operable).

**Comment by sylvainlg** [comment]
Hello Kevin,

I has been busy at work recently. I will have time to test `next7` or 3.0.0 release next week if all goes well :)

**Comment by KevinAst** [comment]
**feature-redux** V3 has been released that includes this PR (accepting client-supplied enhancers)!

**Pull request closed without merging**
